version: "3"

volumes:
  db:

services:

  app:
    build: .
    ports:
      - 8000:80
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    links:
      - db

  db:
    image: postgres:9.6.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=secret
    volumes:
      - db:/var/lib/postgresql/data
