version: "3"

volumes:
  db:
  minio:

services:

  app:
    build: .
    ports:
      - 8000:80
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - STORE_ENDPOINT=minio:9000
    links:
      - db
      - minio

  db:
    image: postgres:9.6.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=secret
    volumes:
      - db:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: access-key
      MINIO_SECRET_KEY: secret-key
    command: server /data
    volumes:
      - minio:/data
